### ISSUE TITLE
mycms verify don't check the signature

### ISSUE THREAD

**Issue by gilweis** [alonbl/mycms#1]
https://github.com/alonbl/mycms/blob/master/src/libmycms/mycms-core-verify.c
mycms_verify()
Please add call to CMS_SignerInfo_verify() before calling to CMS_SignerInfo_verify_content().
CMS_SignerInfo_verify_content() assume that signatures on digests already checked at  CMS_SignerInfo_verify() and only check the digests on the content if the digests exist in CMS_SignerInfo. If the digests not exist in CMS_SignerInfo, CMS_SignerInfo_verify_content() calculate the value and check the signatures.

**Comment by alonbl** [comment]
Thanks!
Please checkout https://github.com/alonbl/mycms/pull/2
