### ISSUE TITLE
mycms-tool sign/encrypt with pkcs11 and keyopt

### ISSUE THREAD

**Issue by gilweis** [alonbl/mycms#12]
mycms-tool version 0.2.0  sign/encrypt with pkcs11 and keyopt fails with error:
ERROR: 00000005: Invalid keyopts 'rsa_padding_mode=pkcs1' no separator

$ mycms-tool ...... --keyopt="rsa_padding_mode=pkcs1'"

Test scripts with pkcs11 don't run mycms-tool keyopt options.

With version 0.1.1 it's ok

**Comment by alonbl** [comment]
Working for me with the following, I think that you can do better, please find someone that is capable of finding the issue and submit patches or at least refer to the place in code where there is an issue, you should maintain this package, it is not a general use.

```diff
diff --git a/test/mycms-tool/sign/test-pkcs11.sh b/test/mycms-tool/sign/test-pkcs11.sh
index c1f66b0..8acbf5e 100755
--- a/test/mycms-tool/sign/test-pkcs11.sh
+++ b/test/mycms-tool/sign/test-pkcs11.sh
@@ -114,6 +114,7 @@ test_sanity() {
                --data-in="${DATA}" \
                --signer-cert="pkcs11:module=${SOFTHSM2_MODULE}:token-label=token1:cert-label=test1" \
                --signer-cert-pass="token=pass=secret" \
+               --keyopt="rsa_padding_mode:pkcs1" \
                || die "sanity.sign.test1"
 
        echo "List signers test1"
```

**Comment by gilweis** [comment]
Thanks,
It worked for me too with this change (openssl 3.10).
The issue was with openssl 1.1.1.
I'll try to find the issue.
Update:
Tested with clean OS/openssl 1.1.1 and the tests passed.

**Comment by gilweis** [comment]
I found that the problem was with the parameter.
In the past "rsa_padding_mode=pkcs1" worked and now the parameter should be "rsa_padding_mode:pkcs1"
