### ISSUE TITLE
make check - Easy-RSA error

### ISSUE THREAD

**Issue by gilweis** [alonbl/mycms#5]
$ /usr/share/easy-rsa/easyrsa --help
Easy-RSA 3 usage and overview
...

$ make check
...
Making check in test
make[1]: Entering directory '/tmp/mycms/test'
Making check in ca
make[2]: Entering directory '/tmp/mycms/test/ca'
make  check-local
make[3]: Entering directory '/tmp/mycms/test/ca'
rm -f built.rootca init-pki
/usr/share/easy-rsa/easyrsa --vars="./rootca.vars" init-pki

Easy-RSA error:

Use of '--vars=FILE init-pki' is prohibited, use '--pki-dir=DIR'

Host: nix | Linux | /bin/bash

make[3]: *** [Makefile:506: built.rootca] Error 1
make[3]: Leaving directory '/tmp/mycms/test/ca'
make[2]: *** [Makefile:374: check-am] Error 2
make[2]: Leaving directory '/tmp/mycms/test/ca'
make[1]: *** [Makefile:381: check-recursive] Error 1
make[1]: Leaving directory '/tmp/mycms/test'
make: *** [Makefile:566: check-recursive] Error 1

**Comment by alonbl** [comment]
This is probably an old ubuntu, you use some fake easy-rsa (pkitool)
instead of the real one.

**Comment by gilweis** [comment]
I'm using new Ubuntu:
Ubuntu 23.04

**Comment by alonbl** [comment]
Oh... so patches are welcomed :)

**Comment by gilweis** [comment]
$ apt search easy-rsa
easy-rsa/lunar,lunar,now 3.1.0-0.2 all [installed]
  Simple shell based CA utility

**Comment by alonbl** [comment]
You should check what changed in version 3.1 compared to 3.0 and how to
workaround so that tests support both.

**Comment by alonbl** [comment]
see [1]

[1] https://github.com/OpenVPN/easy-rsa/commit/48f7ed5f103689f6a3d8c5ee05d14ea58e3dd743

**Comment by alonbl** [comment]
Fixed in 9f498dc0bb197b812a16d3cc5a25452a6df21f0f
