### ISSUE TITLE
Unable to use windows filenames as parameter

### ISSUE THREAD

**Issue by gilweis** [alonbl/mycms#7]
Unable o use windows filenames that contains ":" like:
--signer-cert="pkcs11:module=C:\Program Files\Yubico\Yubico PIV Tool\bin\libykcs11.dll"

https://github.com/alonbl/mycms/blob/6be2f9b5849e64e6e75213c8193cf323122034dc/src/libmycms/mycms-core-sign.c#L127
https://github.com/alonbl/mycms/blob/6be2f9b5849e64e6e75213c8193cf323122034dc/src/libmycms/mycms-core-encrypt.c#L89

p = strchr(opt, ':') search ':' and then the module get the value of "C"

**Comment by alonbl** [comment]
It support escaping, please try to add ‘\’.
The correct code is [1] if I remember correctly.
I am not sure you use keyopts. But due to OpenSSL change I had to change
the format as order is important.

[1] https://github.com/alonbl/mycms/blob/master/src/mycms-tool/util.c#L47

**Comment by gilweis** [comment]
Thanks,
I tried with "module=C\:\\Program Files\\Yubico\\Yubico PIV Tool\\bin\\libykcs11.dll" and it's work well.
