### ISSUE TITLE
mycms-tool encrypt with --cipher AES-256-CTR failed

### ISSUE THREAD

**Issue by gilweis** [alonbl/mycms#9]
$ mycms-tool --verbose encrypt --cms-out /tmp/payload.cms --data-pt /tmp/payload.bin --data-ct /tmp/payload.enc --to=/tmp/cert.der --cipher AES-256-CTR

ERROR: 00100004: CMS serialization failed
MYCMS ERROR DUMP - BEGIN
Version: mycms-0.2.0_master ()
Entries (most recent call last):
    #0
        SOURCE_FILE=mycms-core-encrypt.c
        SOURCE_LINE=246
        SOURCE_FUNC=mycms_encrypt
        HINT=core.encrypt.encrypt
        CODE=0x00100004
        AUTHORITATIVE=1
        DESCRIPTION=CMS serialization failed
        OPENSSL_STATUS=109838592
        OPENSSL_STATUS_STR=40ECFB81A97F0000:error:068000DE:asn1 encoding routines:asn1_template_ex_i2d:illegal zero content:../crypto/asn1/tasn_enc.c:374:
40ECFB81A97F0000:error:068C0100:asn1 encoding routines:ASN1_item_i2d_bio:malloc failure:../crypto/asn1/a_i2d_fp.c:94:

MYCMS ERROR DUMP - END

**Comment by alonbl** [comment]
please confirm that it works properly with plain openssl.

**Comment by gilweis** [comment]
It's not working with openssl command (OpenSSL 3.0.8)
No error from the command (return 0) and the output cms file is corrupted.

**Comment by alonbl** [comment]
The appropriate channel is the openssl forum to acknowledge the issue and then open a bug in openssl github and work directly with the developers to resolve the issue.

**Comment by gilweis** [comment]
https://github.com/openssl/openssl/pull/22392

**Comment by alonbl** [comment]
> [openssl/openssl#22392](https://github.com/openssl/openssl/pull/22392)

Nice! these many bugs related to CMS but at least they attend them.
